project:
  type: website
  output-dir: docs

website:
  back-to-top-navigation: true
  title: "IUT"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Stratégie à l'international"
        href: strategie_a_l_international.qmd
      - text: "Opérations à l'international"
        href: operations_a_l_international.qmd
      - text: "Marketing"
        href: marketing.qmd
      - text: "Vente"
        href: vente.qmd


format:
  html:
    toc: true
    depth: 3
    numbered: true
    mainfont: Arial
    fontsize: "1.2em"
    linestretch: 1.5
  pdf:
    toc: true
    depth: 3
    numbered: true
    figtab: true
    mainfont: Times New Roman
    colorlinks: true
  docx:
    toc: true
    depth: 3
  epub:
    toc: true
    depth: 3
    mainfont: Verdana

theme:
  light: flatly
  dark: darkly
